name: PyTorchTutorial
channels:
  - anaconda
  - pytorch
  - nvidia
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - absl-py=2.1.0
  - albucore=0.0.24
  - albumentations=2.0.8
  - annotated-types=0.6.0
  - anyio=4.9.0
  - aom=3.6.0
  - appdirs=1.4.4
  - argon2-cffi=23.1.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.3.0
  - asttokens=3.0.0
  - async-lru=2.0.5
  - attrs=25.3.0
  - babel=2.17.0
  - beautifulsoup4=4.13.3
  - blas=1.0
  - bleach=6.2.0
  - bleach-with-css=6.2.0
  - bottleneck=1.4.2
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2025.8.3
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cairo=1.16.0
  - certifi=2025.8.3
  - cffi=1.17.1
  - charset-normalizer=3.3.2
  - click=8.1.8
  - comm=0.2.2
  - contourpy=1.3.1
  - cryptography=45.0.5
  - cuda-cudart=12.4.127
  - cuda-cupti=12.4.127
  - cuda-libraries=12.4.1
  - cuda-nvrtc=12.4.127
  - cuda-nvtx=12.4.127
  - cuda-opencl=12.8.90
  - cuda-runtime=12.4.1
  - cuda-version=12.8
  - cycler=0.11.0
  - cyrus-sasl=2.1.28
  - dav1d=1.2.1
  - dbus=1.13.18
  - debugpy=1.8.11
  - decorator=5.2.1
  - defusedxml=0.7.1
  - dnspython=2.4.2
  - docker-pycreds=0.4.0
  - eigen=3.4.0
  - email-validator=2.3.0
  - email_validator=2.3.0
  - eval-type-backport=0.2.2
  - eval_type_backport=0.2.2
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - expat=2.7.0
  - fastapi-cli=0.0.8
  - fastapi-core=0.116.1
  - ffmpeg=6.1.1
  - filelock=3.17.0
  - fontconfig=2.14.2
  - fonttools=4.55.3
  - fqdn=1.5.1
  - freetype=2.13.3
  - gflags=2.2.2
  - giflib=5.2.2
  - gitdb=4.0.7
  - gitpython=3.1.43
  - glib=2.84.2
  - glib-tools=2.84.2
  - glog=0.5.0
  - gmp=6.3.0
  - gmpy2=2.2.1
  - gnutls=3.8.7
  - graphite2=1.3.14
  - grpcio=1.71.0
  - gst-plugins-base=1.24.12
  - gstreamer=1.24.12
  - gstreamer-orc=0.4.41
  - h11=0.14.0
  - h2=4.2.0
  - harfbuzz=10.2.0
  - hdf5=1.14.5
  - hpack=4.1.0
  - httpcore=1.0.7
  - httptools=0.6.4
  - httpx=0.28.1
  - hyperframe=6.1.0
  - icu=73.1
  - idna=3.7
  - importlib-metadata=8.6.1
  - importlib_resources=6.5.2
  - intel-openmp=2023.1.0
  - ipykernel=6.29.5
  - ipython=9.1.0
  - ipython_pygments_lexers=1.1.1
  - isoduration=20.11.0
  - jedi=0.19.2
  - jinja2=3.1.6
  - joblib=1.4.2
  - jpeg=9e
  - json5=0.10.0
  - jsonpointer=2.1
  - jsonschema=4.23.0
  - jsonschema-specifications=2024.10.1
  - jsonschema-with-format-nongpl=4.23.0
  - jupyter-lsp=2.2.5
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - jupyter_events=0.12.0
  - jupyter_server=2.15.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.3.6
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.3
  - kiwisolver=1.4.8
  - krb5=1.20.1
  - lame=3.100
  - lcms2=2.16
  - ld_impl_linux-64=2.40
  - leptonica=1.82.0
  - lerc=4.0.0
  - libabseil=20250127.0
  - libarchive=3.7.7
  - libclang13=14.0.6
  - libcublas=12.4.5.8
  - libcufft=11.2.1.3
  - libcufile=1.13.0.11
  - libcups=2.4.2
  - libcurand=10.3.9.55
  - libcurl=8.12.1
  - libcusolver=11.6.1.9
  - libcusparse=12.3.1.170
  - libdeflate=1.22
  - libedit=3.1.20230828
  - libev=4.33
  - libexpat=2.7.0
  - libffi=3.4.4
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgl=1.7.0
  - libglib=2.84.2
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=14.2.0
  - libgrpc=1.71.0
  - libiconv=1.16
  - libidn2=2.3.4
  - libjpeg-turbo=2.1.4
  - libllvm14=14.0.6
  - libnghttp2=1.57.0
  - libnpp=12.2.5.30
  - libnsl=2.0.1
  - libnvfatbin=12.8.55
  - libnvjitlink=12.4.127
  - libnvjpeg=12.3.1.117
  - libogg=1.3.5
  - libopus=1.3.1
  - libpng=1.6.39
  - libpq=17.4
  - libprotobuf=5.29.3
  - libre2-11=2024.07.02
  - libsodium=1.0.18
  - libsqlite=3.46.0
  - libssh2=1.11.1
  - libstdcxx=14.2.0
  - libstdcxx-ng=11.2.0
  - libtasn1=4.19.0
  - libtheora=1.1.1
  - libtiff=4.7.0
  - libunistring=0.9.10
  - libuuid=2.38.1
  - libuv=1.48.0
  - libvorbis=1.3.7
  - libvpx=1.13.1
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxcrypt=4.4.36
  - libxkbcommon=1.0.1
  - libxml2=2.13.7
  - libxslt=1.1.41
  - libzlib=1.2.13
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - markdown=3.4.1
  - markdown-it-py=4.0.0
  - markupsafe=3.0.2
  - matplotlib=3.10.1
  - matplotlib-base=3.10.1
  - matplotlib-inline=0.1.7
  - mdurl=0.1.0
  - minizip=4.0.3
  - mistune=3.1.3
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - mysql=8.4.0
  - nbclient=0.10.2
  - nbconvert-core=7.16.6
  - nbformat=5.10.4
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - nettle=3.7.3
  - networkx=3.4.2
  - notebook-shim=0.2.4
  - nspr=4.35
  - nss=3.89.1
  - numexpr=2.10.1
  - numpy=2.2.4
  - numpy-base=2.2.4
  - ocl-icd=2.3.2
  - opencv=4.10.0
  - openh264=2.1.1
  - openjpeg=2.5.2
  - openldap=2.6.4
  - openssl=3.5.2
  - overrides=7.7.0
  - packaging=24.2
  - pandas=2.2.3
  - pandocfilters=1.5.0
  - parso=0.8.4
  - patsy=1.0.1
  - pcre2=10.42
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.1.0
  - pip=25.0
  - pixman=0.40.0
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.3.7
  - prometheus_client=0.21.1
  - prompt-toolkit=3.0.50
  - prompt_toolkit=3.0.50
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pycparser=2.22
  - pydantic=2.10.3
  - pydantic-core=2.27.1
  - pygments=2.19.1
  - pyparsing=3.2.0
  - pyside6=6.7.2
  - pysocks=1.7.1
  - python=3.12.2
  - python-dateutil=2.9.0post0
  - python-dotenv=1.1.0
  - python-fastjsonschema=2.21.1
  - python-json-logger=3.2.1
  - python-multipart=0.0.20
  - python-tzdata=2023.3
  - python_abi=3.12
  - pytorch=2.4.0
  - pytorch-cuda=12.4
  - pytorch-mutex=1.0
  - pytz=2025.1
  - pyyaml=6.0.2
  - pyzmq=26.2.0
  - qhull=2020.2
  - qtbase=6.7.3
  - qtdeclarative=6.7.3
  - qtshadertools=6.7.3
  - qtsvg=6.7.3
  - qttools=6.7.3
  - qtwebchannel=6.7.3
  - qtwebengine=6.7.2
  - qtwebsockets=6.7.3
  - re2=2024.07.02
  - readline=8.2
  - referencing=0.36.2
  - requests=2.32.3
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rich=13.9.4
  - rich-toolkit=0.15.0
  - rpds-py=0.22.3
  - scikit-learn=1.7.1
  - scipy=1.15.2
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - send2trash=1.8.3
  - sentry-sdk=2.18.0
  - setproctitle=1.2.2
  - setuptools=72.1.0
  - shellingham=1.5.0
  - simsimd=6.5.0
  - six=1.17.0
  - smmap=4.0.0
  - sniffio=1.3.1
  - soupsieve=2.5
  - sqlite=3.45.3
  - stack_data=0.6.3
  - starlette=0.46.2
  - statsmodels=0.14.4
  - stringzilla=3.12.6
  - tbb=2021.8.0
  - tensorboard=2.19.0
  - tensorboard-data-server=0.7.0
  - terminado=0.18.1
  - tesseract=5.2.0
  - threadpoolctl=3.5.0
  - tinycss2=1.4.0
  - tk=8.6.14
  - tomli=2.2.1
  - torchtriton=3.0.0
  - torchvision=0.19.0
  - tornado=6.4.2
  - traitlets=5.14.3
  - typer=0.16.1
  - typer-slim=0.16.1
  - typer-slim-standard=0.16.1
  - types-python-dateutil=2.9.0.20241206
  - typing=3.10.0.0
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - typing_utils=0.1.0
  - tzdata=2025a
  - unicodedata2=15.1.0
  - uri-template=1.3.0
  - urllib3=2.3.0
  - uvicorn-standard=0.35.0
  - uvloop=0.21.0
  - wandb=0.19.9
  - watchfiles=0.24.0
  - wcwidth=0.2.13
  - webcolors=24.11.1
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - websockets=15.0.1
  - werkzeug=3.1.3
  - wheel=0.45.1
  - xcb-util-cursor=0.1.4
  - xorg-kbproto=1.0.7
  - xorg-libx11=1.8.9
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.6.4
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.21.0
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - aiofiles==24.1.0
      - alembic==1.15.2
      - blessed==1.21.0
      - blinker==1.9.0
      - brotli==1.1.0
      - cachetools==5.5.2
      - cloudpickle==3.1.1
      - databricks-sdk==0.50.0
      - deprecated==1.2.18
      - docker==7.1.0
      - fastapi==0.115.12
      - ffmpy==0.6.1
      - flask==3.1.0
      - fsspec==2025.3.2
      - google-auth==2.39.0
      - gpustat==1.1.1
      - gputil==1.4.0
      - gradio==5.44.1
      - gradio-client==1.12.1
      - graphene==3.4.3
      - graphql-core==3.2.6
      - graphql-relay==3.2.0
      - graphviz==0.20.3
      - greenlet==3.2.0
      - groovy==0.1.2
      - gunicorn==23.0.0
      - hf-xet==1.1.8
      - huggingface-hub==0.34.4
      - itsdangerous==2.2.0
      - kagglehub==0.3.12
      - mako==1.3.10
      - mlflow==2.21.3
      - mlflow-skinny==2.21.3
      - nvidia-ml-py==13.580.65
      - onnx==1.18.0
      - opentelemetry-api==1.32.1
      - opentelemetry-sdk==1.32.1
      - opentelemetry-semantic-conventions==0.53b1
      - orjson==3.11.3
      - protobuf==4.25.6
      - pyarrow==19.0.1
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pydub==0.25.1
      - regex==2025.7.34
      - rsa==4.9
      - ruff==0.12.11
      - safehttpx==0.1.6
      - safetensors==0.5.3
      - semantic-version==2.10.0
      - sqlalchemy==2.0.40
      - sqlparse==0.5.3
      - sympy==1.13.1
      - timm==1.0.15
      - tokenizers==0.21.4
      - tomlkit==0.13.3
      - torchinfo==1.8.0
      - torchviz==0.0.3
      - tqdm==4.67.1
      - transformers==4.56.0.dev0
      - uvicorn==0.34.1
      - wrapt==1.17.2
