# MNIST Model Configuration

# Data parameters
data:
  batch_size: 64
  val_split: 0.2
  num_workers: 2
  pin_memory: true

# Model parameters
model:
  input_dim: 784  # 28x28
  hidden_dim: 256
  output_dim: 10
  dropout: 0.5

# Training parameters
training:
  learning_rate: 0.001
  weight_decay: 0.0001
  num_epochs: 10
  patience: 5
  scheduler:
    step_size: 10
    gamma: 0.5

# Experiment parameters
experiment:
  save_dir: "experiments"
  seed: 42
