model:
  name: resnet18
  weights: "models.ResNet18_Weights.IMAGENET1K_V1"  # or null
  num_classes: 3
  lr: 0.001

dataset:
  path: ./data/brain-cancer
  img_size: 224
  batch_size: 256
  num_workers: 4
  pin_memory: true
  train_split: 0.7
  val_split: 0.15
  test_split: 0.15
  seed: 42

transform:
  augmentation: true

train:
  epochs: 50
  save_every: 5