dataset:
  batch_size: 64
  img_size: 224
  num_workers: 8
  path: ./data/brain-cancer/Brain_Cancer raw MRI data/Brain_Cancer
  persistent_workers: true
  pin_memory: true
  prefetch_factor: 4
  seed: 42
  test_split: 0.15
  train_split: 0.7
  val_split: 0.15
model: swin_t
models:
  efficientnet_b0:
    batch_size: 32
    lr: 0.001
    name: efficientnet_b0
    num_classes: 3
    weights: models.EfficientNet_B0_Weights.IMAGENET1K_V1
  medical_cnn:
    batch_size: 64
    lr: 0.001
    name: medical_cnn
    num_classes: 3
    weights: models.EfficientNet_B0_Weights.IMAGENET1K_V1
  resnet18:
    batch_size: 128
    lr: 0.0001
    name: resnet18
    num_classes: 3
    weights: models.ResNet18_Weights.IMAGENET1K_V1
  resnet50:
    batch_size: 64
    lr: 0.001
    name: resnet50
    num_classes: 3
    weights: models.ResNet50_Weights.IMAGENET1K_V1
  swin_s:
    batch_size: 8
    lr: 0.0001
    name: swin_s
    num_classes: 3
    weights: models.Swin_S_Weights.IMAGENET1K_V1
  swin_t:
    batch_size: 32
    lr: 5.0e-05
    name: swin_t
    num_classes: 3
    weights: models.Swin_T_Weights.IMAGENET1K_V1
  vit_b_16:
    batch_size: 16
    lr: 0.0001
    name: vit_b_16
    num_classes: 3
    weights: models.ViT_B_16_Weights.IMAGENET1K_V1
  xception_medical:
    batch_size: 16
    img_size: 299
    lr: 0.001
    name: xception_medical
    num_classes: 3
    weights: models.EfficientNet_B0_Weights.IMAGENET1K_V1
monitoring:
  mlflow_experiment_name: brain-cancer-mri-v2
  mlflow_tracking_uri: ./mlruns
  tensorboard_log_dir: ./runs
  wandb:
    entity: null
    name: null
    notes: Brain tumor classification using deep learning
    project: brain-cancer-mri
    tags:
    - brain-tumor
    - classification
    - pytorch
performance:
  benchmark_cudnn: true
  channels_last: false
  compile_model: false
  gradient_accumulation: 1
  max_grad_norm: 1.0
  mixed_precision: false
train:
  epochs: 10
  min_delta: 0.001
  output_dir: ./checkpoints
  patience: 10
  save_every: 5
transform:
  augmentation: true
